image:
  repository: "" # to be filled with ECR repository URL
  tag: "latest"

service:
  type: LoadBalancer
  port: 8000

replicaCount: 2

resources:
  requests:
    cpu: 250m
    memory: 256Mi
  limits:
    cpu: 500m
    memory: 512Mi

readinessProbe:
  httpGet:
    path: /
    port: 8000
  initialDelaySeconds: 10
  periodSeconds: 10

livenessProbe:
  httpGet:
    path: /
    port: 8000
  initialDelaySeconds: 30
  periodSeconds: 20

startupProbe:
  httpGet:
    path: /
    port: 8000
  failureThreshold: 30
  periodSeconds: 10

env:
  POSTGRES_HOST: "" # Replace via CI/CD or use Kubernetes Secret
  POSTGRES_PORT: "5432"
  POSTGRES_DB: "djangodb"
  POSTGRES_USER: "dbadmin"
  POSTGRES_PASSWORD: "" # Replace via CI/CD or use Kubernetes Secret

hpa:
  enabled: true
  minReplicas: 2
  maxReplicas: 6
  targetCPUUtilizationPercentage: 70
